package aplcovid19.project;
import aplcovid19.koneksi.koneksi;
import javax.swing.*;
import java.sql.*; // Fungsi Import yang digunakan untuk SQL
import java.awt.Color;

/**
 * @author 
 * Nama  : Rachman Aldiansyah   (10119038)
 *         Diva Sabila Ramadhan (10119039)
 *         Agus Deri Dermawan   (10119040)
 * Kelas : IF-1
 */

public class loginView extends javax.swing.JFrame {
    // deklarasi Variabel
    koneksi dbsetting;
    String driver,database,user,pass;
    Object tabel;
    
    public loginView() {
        initComponents();
        dbsetting = new koneksi();
        driver    = dbsetting.SettingPanel("DBDriver");
        database  = dbsetting.SettingPanel("DBDatabase");
        user      = dbsetting.SettingPanel("DBUsername");
        pass      = dbsetting.SettingPanel("DBPassword");
        
        // setting no-resize
        setExtendedState(JFrame.MAXIMIZED_HORIZ);
        setVisible(true);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        logoPanel = new javax.swing.JPanel();
        logoIcons = new javax.swing.JLabel();
        userPanel = new javax.swing.JPanel();
        userIcons = new javax.swing.JLabel();
        txt_username = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        passIcons = new javax.swing.JLabel();
        txt_password = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        btn_signin = new javax.swing.JButton();
        btn_signup = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AplCovid19");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoPanel.setBackground(new java.awt.Color(236, 240, 241));

        logoIcons.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplcovid19/img/covid-logo_1.png"))); // NOI18N

        javax.swing.GroupLayout logoPanelLayout = new javax.swing.GroupLayout(logoPanel);
        logoPanel.setLayout(logoPanelLayout);
        logoPanelLayout.setHorizontalGroup(
            logoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoPanelLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(logoIcons)
                .addContainerGap(42, Short.MAX_VALUE))
        );
        logoPanelLayout.setVerticalGroup(
            logoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoPanelLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(logoIcons)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        background.add(logoPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 510));

        userPanel.setBackground(new java.awt.Color(41, 128, 185));

        userIcons.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        userIcons.setForeground(new java.awt.Color(236, 240, 241));
        userIcons.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplcovid19/img/user-icons.png"))); // NOI18N
        userIcons.setText("USERNAME");

        txt_username.setBackground(new java.awt.Color(41, 128, 185));
        txt_username.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        txt_username.setForeground(new java.awt.Color(236, 240, 241));
        txt_username.setBorder(null);

        passIcons.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        passIcons.setForeground(new java.awt.Color(236, 240, 241));
        passIcons.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplcovid19/img/pass-icons.png"))); // NOI18N
        passIcons.setText("PASSWORD");

        txt_password.setBackground(new java.awt.Color(41, 128, 185));
        txt_password.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        txt_password.setForeground(new java.awt.Color(236, 240, 241));
        txt_password.setBorder(null);

        btn_signin.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btn_signin.setForeground(new java.awt.Color(236, 240, 241));
        btn_signin.setText("Sign In");
        btn_signin.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(236, 240, 241), 2, true));
        btn_signin.setContentAreaFilled(false);
        btn_signin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_signinMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_signinMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_signinMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_signinMouseReleased(evt);
            }
        });
        btn_signin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_signinActionPerformed(evt);
            }
        });

        btn_signup.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btn_signup.setForeground(new java.awt.Color(236, 240, 241));
        btn_signup.setText("Sign Up");
        btn_signup.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(236, 240, 241), 2, true));
        btn_signup.setContentAreaFilled(false);
        btn_signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_signupActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(236, 240, 241));
        jLabel1.setText("Forget Password?");

        javax.swing.GroupLayout userPanelLayout = new javax.swing.GroupLayout(userPanel);
        userPanel.setLayout(userPanelLayout);
        userPanelLayout.setHorizontalGroup(
            userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userPanelLayout.createSequentialGroup()
                .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(userPanelLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passIcons)
                            .addComponent(userIcons)))
                    .addGroup(userPanelLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txt_password, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_username, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, userPanelLayout.createSequentialGroup()
                                .addComponent(btn_signin, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_signup, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(40, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(101, 101, 101))
        );
        userPanelLayout.setVerticalGroup(
            userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userPanelLayout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(userIcons)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_username, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passIcons)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_signin, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_signup, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(52, 52, 52))
        );

        background.add(userPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, 320, 510));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 799, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_signinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_signinActionPerformed
        // validasi userLogin
        try {
            Class.forName(driver);
            Connection kon = DriverManager.getConnection(database,user,pass);
            String SQL = "SELECT * FROM tblogin WHERE username='"+txt_username.getText()+"' AND password='"+txt_password.getText()+"'";
            Statement stt = kon.createStatement();
            ResultSet res = stt.executeQuery(SQL);
            if(res.next()) {
            if(txt_username.getText().equals(res.getString("username")) && txt_password.getText().equals(res.getString("password"))) {
               JOptionPane.showMessageDialog(null, "Login Behasil, Selamat Datang! "+txt_username.getText());
               // pindah ke panel menuView
               menuView login = new menuView();
               login.setVisible(true);
               this.setVisible(false);
            }
            } else {
                JOptionPane.showMessageDialog(null, "Username Atau Password Salah. Ulangi!");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(),"Error",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btn_signinActionPerformed

    private void btn_signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_signupActionPerformed
        signupView signUp = new signupView();
        signUp.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_signupActionPerformed

    private void btn_signinMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_signinMouseEntered
        // TODO add your handling code here:
        btn_signin.setBackground(new Color(27,127,194));
    }//GEN-LAST:event_btn_signinMouseEntered

    private void btn_signinMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_signinMouseExited
        // TODO add your handling code here:
        btn_signin.setBackground(new Color(52,152,219));
    }//GEN-LAST:event_btn_signinMouseExited

    private void btn_signinMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_signinMousePressed
        // TODO add your handling code here:
        btn_signin.setBackground(new Color(1,101,168));
    }//GEN-LAST:event_btn_signinMousePressed

    private void btn_signinMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_signinMouseReleased
        // TODO add your handling code here:
        btn_signin.setBackground(new Color(52,152,219));
    }//GEN-LAST:event_btn_signinMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JButton btn_signin;
    private javax.swing.JButton btn_signup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel logoIcons;
    private javax.swing.JPanel logoPanel;
    private javax.swing.JLabel passIcons;
    private javax.swing.JTextField txt_password;
    private javax.swing.JTextField txt_username;
    private javax.swing.JLabel userIcons;
    private javax.swing.JPanel userPanel;
    // End of variables declaration//GEN-END:variables
}
