/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplcovid19.project;
import javax.swing.*;
import java.awt.Color;

/**
 *
 * @author RACHMAN
 */
public class menuView extends javax.swing.JFrame {

    /**
     * Creates new form menuView
     */
    public menuView() {
        initComponents();
        // setting no-resize
        setExtendedState(JFrame.MAXIMIZED_HORIZ);
        setVisible(true);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        sidePanel = new javax.swing.JPanel();
        btn_showData = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btn_deleteData = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btn_home = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btn_announcement = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_addData = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_updateData = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btn_exit = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        mainPanel = new javax.swing.JPanel();
        homePanel = new javax.swing.JPanel();
        titlePanel = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        annsPanel = new javax.swing.JPanel();
        titlePanel3 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        addPanel = new javax.swing.JPanel();
        titlePanel1 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        updatePanel = new javax.swing.JPanel();
        titlePanel4 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        deletePanel = new javax.swing.JPanel();
        titlePanel5 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        showPanel = new javax.swing.JPanel();
        titlePanel6 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Beranda");

        background.setBackground(new java.awt.Color(236, 240, 241));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidePanel.setBackground(new java.awt.Color(41, 128, 185));
        sidePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_showData.setBackground(new java.awt.Color(9, 132, 227));
        btn_showData.setForeground(new java.awt.Color(189, 195, 199));
        btn_showData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_showDataMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_showDataMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_showDataMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_showDataMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_showDataMouseReleased(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplcovid19/img/document_32px.png"))); // NOI18N
        jLabel4.setToolTipText("");

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(236, 240, 241));
        jLabel10.setText("Show Data COVID-19");

        javax.swing.GroupLayout btn_showDataLayout = new javax.swing.GroupLayout(btn_showData);
        btn_showData.setLayout(btn_showDataLayout);
        btn_showDataLayout.setHorizontalGroup(
            btn_showDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_showDataLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addContainerGap(46, Short.MAX_VALUE))
        );
        btn_showDataLayout.setVerticalGroup(
            btn_showDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_showDataLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addContainerGap())
        );

        sidePanel.add(btn_showData, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 270, 50));

        btn_deleteData.setBackground(new java.awt.Color(52, 152, 219));
        btn_deleteData.setForeground(new java.awt.Color(189, 195, 199));
        btn_deleteData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_deleteDataMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_deleteDataMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_deleteDataMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_deleteDataMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_deleteDataMouseReleased(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplcovid19/img/trash_can_32px.png"))); // NOI18N
        jLabel5.setToolTipText("");

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(236, 240, 241));
        jLabel9.setText("Delete Data COVID-19");

        javax.swing.GroupLayout btn_deleteDataLayout = new javax.swing.GroupLayout(btn_deleteData);
        btn_deleteData.setLayout(btn_deleteDataLayout);
        btn_deleteDataLayout.setHorizontalGroup(
            btn_deleteDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_deleteDataLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        btn_deleteDataLayout.setVerticalGroup(
            btn_deleteDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_deleteDataLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addContainerGap())
        );

        sidePanel.add(btn_deleteData, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 270, 50));

        btn_home.setBackground(new java.awt.Color(52, 152, 219));
        btn_home.setForeground(new java.awt.Color(189, 195, 199));
        btn_home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_homeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_homeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_homeMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_homeMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_homeMouseReleased(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplcovid19/img/home_32px.png"))); // NOI18N
        jLabel6.setToolTipText("");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(236, 240, 241));
        jLabel1.setText("Home");

        javax.swing.GroupLayout btn_homeLayout = new javax.swing.GroupLayout(btn_home);
        btn_home.setLayout(btn_homeLayout);
        btn_homeLayout.setHorizontalGroup(
            btn_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_homeLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addContainerGap(148, Short.MAX_VALUE))
        );
        btn_homeLayout.setVerticalGroup(
            btn_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_homeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        sidePanel.add(btn_home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 270, 50));

        btn_announcement.setBackground(new java.awt.Color(9, 132, 227));
        btn_announcement.setForeground(new java.awt.Color(189, 195, 199));
        btn_announcement.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_announcementMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_announcementMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_announcementMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_announcementMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_announcementMouseReleased(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplcovid19/img/commercial_32px.png"))); // NOI18N
        jLabel7.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(236, 240, 241));
        jLabel2.setText("Announcement");

        javax.swing.GroupLayout btn_announcementLayout = new javax.swing.GroupLayout(btn_announcement);
        btn_announcement.setLayout(btn_announcementLayout);
        btn_announcementLayout.setHorizontalGroup(
            btn_announcementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_announcementLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addContainerGap(82, Short.MAX_VALUE))
        );
        btn_announcementLayout.setVerticalGroup(
            btn_announcementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_announcementLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        sidePanel.add(btn_announcement, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 270, 50));

        btn_addData.setBackground(new java.awt.Color(52, 152, 219));
        btn_addData.setForeground(new java.awt.Color(189, 195, 199));
        btn_addData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_addDataMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_addDataMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_addDataMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_addDataMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_addDataMouseReleased(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplcovid19/img/add_32px.png"))); // NOI18N
        jLabel13.setToolTipText("");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(236, 240, 241));
        jLabel3.setText("Add Data COVID-19");

        javax.swing.GroupLayout btn_addDataLayout = new javax.swing.GroupLayout(btn_addData);
        btn_addData.setLayout(btn_addDataLayout);
        btn_addDataLayout.setHorizontalGroup(
            btn_addDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_addDataLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addContainerGap(57, Short.MAX_VALUE))
        );
        btn_addDataLayout.setVerticalGroup(
            btn_addDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_addDataLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        sidePanel.add(btn_addData, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 270, 50));

        btn_updateData.setBackground(new java.awt.Color(9, 132, 227));
        btn_updateData.setForeground(new java.awt.Color(189, 195, 199));
        btn_updateData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_updateDataMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_updateDataMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_updateDataMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_updateDataMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_updateDataMouseReleased(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplcovid19/img/update_32px.png"))); // NOI18N
        jLabel14.setToolTipText("");

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(236, 240, 241));
        jLabel8.setText("Update Data COVID-19");

        javax.swing.GroupLayout btn_updateDataLayout = new javax.swing.GroupLayout(btn_updateData);
        btn_updateData.setLayout(btn_updateDataLayout);
        btn_updateDataLayout.setHorizontalGroup(
            btn_updateDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_updateDataLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        btn_updateDataLayout.setVerticalGroup(
            btn_updateDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_updateDataLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addContainerGap())
        );

        sidePanel.add(btn_updateData, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 270, 50));

        btn_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplcovid19/img/exit_32px.png"))); // NOI18N
        btn_exit.setBorder(null);
        btn_exit.setContentAreaFilled(false);
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });
        sidePanel.add(btn_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 50, 40));

        jSeparator1.setBackground(new java.awt.Color(236, 240, 241));
        sidePanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 210, 10));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(236, 240, 241));
        jLabel11.setText("Data COVID-19");
        sidePanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, -1, -1));

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(236, 240, 241));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplcovid19/img/coronavirus_32px.png"))); // NOI18N
        jLabel12.setText("Aplikasi");
        sidePanel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jPanel3.setBackground(new java.awt.Color(52, 152, 219));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        sidePanel.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 500, 80, 20));

        jPanel4.setBackground(new java.awt.Color(9, 132, 227));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        sidePanel.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 440, 20, 70));

        jPanel5.setBackground(new java.awt.Color(9, 132, 227));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        sidePanel.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 20, 70));

        jPanel6.setBackground(new java.awt.Color(52, 152, 219));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        sidePanel.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 20));

        background.add(sidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 520));

        mainPanel.setBackground(new java.awt.Color(236, 240, 241));
        mainPanel.setLayout(new java.awt.CardLayout());

        homePanel.setBackground(new java.awt.Color(236, 240, 241));

        titlePanel.setBackground(new java.awt.Color(52, 152, 219));

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(236, 240, 241));
        jLabel15.setText("SELAMAT DATANG");

        javax.swing.GroupLayout titlePanelLayout = new javax.swing.GroupLayout(titlePanel);
        titlePanel.setLayout(titlePanelLayout);
        titlePanelLayout.setHorizontalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanelLayout.createSequentialGroup()
                .addGap(185, 185, 185)
                .addComponent(jLabel15)
                .addContainerGap(186, Short.MAX_VALUE))
        );
        titlePanelLayout.setVerticalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel15)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout homePanelLayout = new javax.swing.GroupLayout(homePanel);
        homePanel.setLayout(homePanelLayout);
        homePanelLayout.setHorizontalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        homePanelLayout.setVerticalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanelLayout.createSequentialGroup()
                .addComponent(titlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 443, Short.MAX_VALUE))
        );

        mainPanel.add(homePanel, "card2");

        annsPanel.setBackground(new java.awt.Color(236, 240, 241));

        titlePanel3.setBackground(new java.awt.Color(52, 152, 219));

        jLabel18.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(236, 240, 241));
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplcovid19/img/commercial_32px.png"))); // NOI18N
        jLabel18.setText("PENGUMUMAN");

        javax.swing.GroupLayout titlePanel3Layout = new javax.swing.GroupLayout(titlePanel3);
        titlePanel3.setLayout(titlePanel3Layout);
        titlePanel3Layout.setHorizontalGroup(
            titlePanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanel3Layout.createSequentialGroup()
                .addGap(185, 185, 185)
                .addComponent(jLabel18)
                .addContainerGap(186, Short.MAX_VALUE))
        );
        titlePanel3Layout.setVerticalGroup(
            titlePanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel18)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout annsPanelLayout = new javax.swing.GroupLayout(annsPanel);
        annsPanel.setLayout(annsPanelLayout);
        annsPanelLayout.setHorizontalGroup(
            annsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titlePanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        annsPanelLayout.setVerticalGroup(
            annsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(annsPanelLayout.createSequentialGroup()
                .addComponent(titlePanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 438, Short.MAX_VALUE))
        );

        mainPanel.add(annsPanel, "card2");

        addPanel.setBackground(new java.awt.Color(236, 240, 241));

        titlePanel1.setBackground(new java.awt.Color(52, 152, 219));

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(236, 240, 241));
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplcovid19/img/coronavirus_32px.png"))); // NOI18N
        jLabel16.setText("TAMBAH DATA KORBAN COVID-19");

        javax.swing.GroupLayout titlePanel1Layout = new javax.swing.GroupLayout(titlePanel1);
        titlePanel1.setLayout(titlePanel1Layout);
        titlePanel1Layout.setHorizontalGroup(
            titlePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanel1Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jLabel16)
                .addContainerGap(101, Short.MAX_VALUE))
        );
        titlePanel1Layout.setVerticalGroup(
            titlePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel16)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout addPanelLayout = new javax.swing.GroupLayout(addPanel);
        addPanel.setLayout(addPanelLayout);
        addPanelLayout.setHorizontalGroup(
            addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titlePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        addPanelLayout.setVerticalGroup(
            addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPanelLayout.createSequentialGroup()
                .addComponent(titlePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 438, Short.MAX_VALUE))
        );

        mainPanel.add(addPanel, "card2");

        updatePanel.setBackground(new java.awt.Color(236, 240, 241));

        titlePanel4.setBackground(new java.awt.Color(52, 152, 219));

        jLabel19.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(236, 240, 241));
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplcovid19/img/coronavirus_32px.png"))); // NOI18N
        jLabel19.setText("UPDATE DATA KORBAN COVID-19");

        javax.swing.GroupLayout titlePanel4Layout = new javax.swing.GroupLayout(titlePanel4);
        titlePanel4.setLayout(titlePanel4Layout);
        titlePanel4Layout.setHorizontalGroup(
            titlePanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanel4Layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(jLabel19)
                .addContainerGap(103, Short.MAX_VALUE))
        );
        titlePanel4Layout.setVerticalGroup(
            titlePanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel19)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout updatePanelLayout = new javax.swing.GroupLayout(updatePanel);
        updatePanel.setLayout(updatePanelLayout);
        updatePanelLayout.setHorizontalGroup(
            updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titlePanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        updatePanelLayout.setVerticalGroup(
            updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updatePanelLayout.createSequentialGroup()
                .addComponent(titlePanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 438, Short.MAX_VALUE))
        );

        mainPanel.add(updatePanel, "card2");

        deletePanel.setBackground(new java.awt.Color(236, 240, 241));
        deletePanel.setForeground(new java.awt.Color(236, 240, 241));

        titlePanel5.setBackground(new java.awt.Color(52, 152, 219));

        jLabel20.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(236, 240, 241));
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplcovid19/img/coronavirus_32px.png"))); // NOI18N
        jLabel20.setText("DELETE DATA KORBAN COVID-19");

        javax.swing.GroupLayout titlePanel5Layout = new javax.swing.GroupLayout(titlePanel5);
        titlePanel5.setLayout(titlePanel5Layout);
        titlePanel5Layout.setHorizontalGroup(
            titlePanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, titlePanel5Layout.createSequentialGroup()
                .addContainerGap(104, Short.MAX_VALUE)
                .addComponent(jLabel20)
                .addGap(101, 101, 101))
        );
        titlePanel5Layout.setVerticalGroup(
            titlePanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanel5Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel20)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout deletePanelLayout = new javax.swing.GroupLayout(deletePanel);
        deletePanel.setLayout(deletePanelLayout);
        deletePanelLayout.setHorizontalGroup(
            deletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titlePanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        deletePanelLayout.setVerticalGroup(
            deletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deletePanelLayout.createSequentialGroup()
                .addComponent(titlePanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 438, Short.MAX_VALUE))
        );

        mainPanel.add(deletePanel, "card2");

        showPanel.setBackground(new java.awt.Color(236, 240, 241));
        showPanel.setForeground(new java.awt.Color(236, 240, 241));

        titlePanel6.setBackground(new java.awt.Color(52, 152, 219));

        jLabel21.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(236, 240, 241));
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplcovid19/img/coronavirus_32px.png"))); // NOI18N
        jLabel21.setText("DATA KORBAN COVID-19");

        javax.swing.GroupLayout titlePanel6Layout = new javax.swing.GroupLayout(titlePanel6);
        titlePanel6.setLayout(titlePanel6Layout);
        titlePanel6Layout.setHorizontalGroup(
            titlePanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanel6Layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(jLabel21)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        titlePanel6Layout.setVerticalGroup(
            titlePanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanel6Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel21)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout showPanelLayout = new javax.swing.GroupLayout(showPanel);
        showPanel.setLayout(showPanelLayout);
        showPanelLayout.setHorizontalGroup(
            showPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titlePanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(showPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 516, Short.MAX_VALUE)
                .addContainerGap())
        );
        showPanelLayout.setVerticalGroup(
            showPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(showPanelLayout.createSequentialGroup()
                .addComponent(titlePanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
                .addContainerGap())
        );

        mainPanel.add(showPanel, "card2");

        background.add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 540, 520));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_homeMouseClicked
        // Remove Panel
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        // Add Panel
        mainPanel.add(homePanel);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_btn_homeMouseClicked
    
    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
        // TODO add your handling code here:
        int dialogBtn = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(this, "Anda yakin akan keluar?", "PERINGATAN", dialogBtn);
        loginView login = new loginView();
        login.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_exitActionPerformed

    private void btn_announcementMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_announcementMouseClicked
        // TODO add your handling code here:
        
        // Remove Panel
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        // Add Panel
        mainPanel.add(annsPanel);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_btn_announcementMouseClicked

    private void btn_addDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_addDataMouseClicked
        // TODO add your handling code here:
        
        // Remove Panel
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        // Add Panel
        mainPanel.add(addPanel);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_btn_addDataMouseClicked

    private void btn_updateDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_updateDataMouseClicked
        // TODO add your handling code here:
        
        // Remove Panel
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        // Add Panel
        mainPanel.add(updatePanel);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_btn_updateDataMouseClicked

    private void btn_deleteDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_deleteDataMouseClicked
        // TODO add your handling code here:
        
        // Remove Panel
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        // Add Panel
        mainPanel.add(deletePanel);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_btn_deleteDataMouseClicked

    private void btn_showDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_showDataMouseClicked
        // TODO add your handling code here:
        
        // Remove Panel
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        // Add Panel
        mainPanel.add(showPanel);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_btn_showDataMouseClicked

    private void btn_homeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_homeMouseEntered
        // TODO add your handling code here:
        btn_home.setBackground(new Color(27,127,194));
    }//GEN-LAST:event_btn_homeMouseEntered

    private void btn_homeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_homeMouseExited
        // TODO add your handling code here:
        btn_home.setBackground(new Color(52,152,219));
    }//GEN-LAST:event_btn_homeMouseExited

    private void btn_homeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_homeMousePressed
        // TODO add your handling code here:
        btn_home.setBackground(new Color(1,101,168));
    }//GEN-LAST:event_btn_homeMousePressed

    private void btn_homeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_homeMouseReleased
        // TODO add your handling code here:
        btn_home.setBackground(new Color(52,152,219));
    }//GEN-LAST:event_btn_homeMouseReleased

    private void btn_announcementMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_announcementMouseEntered
        // TODO add your handling code here:
        btn_announcement.setBackground(new Color(0,107,202));
    }//GEN-LAST:event_btn_announcementMouseEntered

    private void btn_announcementMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_announcementMouseExited
        // TODO add your handling code here:
        btn_announcement.setBackground(new Color(9,132,227));
    }//GEN-LAST:event_btn_announcementMouseExited

    private void btn_announcementMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_announcementMousePressed
        // TODO add your handling code here:
        btn_announcement.setBackground(new Color(0,81,176));
    }//GEN-LAST:event_btn_announcementMousePressed

    private void btn_announcementMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_announcementMouseReleased
        // TODO add your handling code here:
        btn_announcement.setBackground(new Color(9,132,227));
    }//GEN-LAST:event_btn_announcementMouseReleased

    private void btn_addDataMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_addDataMouseEntered
        // TODO add your handling code here:
        btn_addData.setBackground(new Color(27,127,194));
    }//GEN-LAST:event_btn_addDataMouseEntered

    private void btn_addDataMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_addDataMouseExited
        // TODO add your handling code here:
        btn_addData.setBackground(new Color(52,152,219));
    }//GEN-LAST:event_btn_addDataMouseExited

    private void btn_addDataMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_addDataMousePressed
        // TODO add your handling code here:
        btn_addData.setBackground(new Color(1,101,168));
    }//GEN-LAST:event_btn_addDataMousePressed

    private void btn_addDataMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_addDataMouseReleased
        // TODO add your handling code here:
        btn_addData.setBackground(new Color(52,152,219));
    }//GEN-LAST:event_btn_addDataMouseReleased

    private void btn_updateDataMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_updateDataMouseEntered
        // TODO add your handling code here:
        btn_updateData.setBackground(new Color(0,107,202));
    }//GEN-LAST:event_btn_updateDataMouseEntered

    private void btn_updateDataMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_updateDataMouseExited
        // TODO add your handling code here:
        btn_updateData.setBackground(new Color(9,132,227));
    }//GEN-LAST:event_btn_updateDataMouseExited

    private void btn_updateDataMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_updateDataMousePressed
        // TODO add your handling code here:
        btn_updateData.setBackground(new Color(0,81,176));
    }//GEN-LAST:event_btn_updateDataMousePressed

    private void btn_updateDataMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_updateDataMouseReleased
        // TODO add your handling code here:
        btn_updateData.setBackground(new Color(9,132,227));
    }//GEN-LAST:event_btn_updateDataMouseReleased

    private void btn_deleteDataMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_deleteDataMouseEntered
        // TODO add your handling code here:
        btn_deleteData.setBackground(new Color(27,127,194));
    }//GEN-LAST:event_btn_deleteDataMouseEntered

    private void btn_deleteDataMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_deleteDataMouseExited
        // TODO add your handling code here:
        btn_deleteData.setBackground(new Color(52,152,219));
    }//GEN-LAST:event_btn_deleteDataMouseExited

    private void btn_deleteDataMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_deleteDataMousePressed
        // TODO add your handling code here:
        btn_deleteData.setBackground(new Color(1,101,168));
    }//GEN-LAST:event_btn_deleteDataMousePressed

    private void btn_deleteDataMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_deleteDataMouseReleased
        // TODO add your handling code here:
        btn_deleteData.setBackground(new Color(52,152,219));
    }//GEN-LAST:event_btn_deleteDataMouseReleased

    private void btn_showDataMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_showDataMouseEntered
        // TODO add your handling code here:
        btn_showData.setBackground(new Color(0,107,202));
    }//GEN-LAST:event_btn_showDataMouseEntered

    private void btn_showDataMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_showDataMouseExited
        // TODO add your handling code here:
        btn_showData.setBackground(new Color(9,132,227));
    }//GEN-LAST:event_btn_showDataMouseExited

    private void btn_showDataMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_showDataMousePressed
        // TODO add your handling code here:
        btn_showData.setBackground(new Color(0,81,176));
    }//GEN-LAST:event_btn_showDataMousePressed

    private void btn_showDataMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_showDataMouseReleased
        // TODO add your handling code here:
        btn_showData.setBackground(new Color(9,132,227));
    }//GEN-LAST:event_btn_showDataMouseReleased

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addPanel;
    private javax.swing.JPanel annsPanel;
    private javax.swing.JPanel background;
    private javax.swing.JPanel btn_addData;
    private javax.swing.JPanel btn_announcement;
    private javax.swing.JPanel btn_deleteData;
    private javax.swing.JButton btn_exit;
    private javax.swing.JPanel btn_home;
    private javax.swing.JPanel btn_showData;
    private javax.swing.JPanel btn_updateData;
    private javax.swing.JPanel deletePanel;
    private javax.swing.JPanel homePanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel showPanel;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JPanel titlePanel;
    private javax.swing.JPanel titlePanel1;
    private javax.swing.JPanel titlePanel3;
    private javax.swing.JPanel titlePanel4;
    private javax.swing.JPanel titlePanel5;
    private javax.swing.JPanel titlePanel6;
    private javax.swing.JPanel updatePanel;
    // End of variables declaration//GEN-END:variables
}
